#Docker Work na BSDK

name: setting up environment

on: [push]
    
env:
  GitHubMail: "error@notavailable.live"
  GitHubName: "ProgrammingError"
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: cloning repo
         continue-on-error: true
         run: |
           sudo apt-get install -y git
           sudo apt-get install --reinstall openssl libssl1.1 libssl-dev libssl-doc
           git config --global user.email ${GitHubMail}
           git config --global user.name ${GitHubName}
           git config --global credential.helper store
           echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
 
       - name: Building Ultroid
         continue-on-error: false
         run: |
            git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.CREDS }} ultroid
            cd ultroid
            docker-compose up -d
            docker-compose logs -f
       
       - name: Loop workflow
         continue-on-error: false
         run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
              
