#Docker Work na BSDK

name: setting up environment

on: [push]
    
env:
  GitHubMail: "error@notavailable.live"
  GitHubName: "ProgrammingError"
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: cloning repo
         continue-on-error: true
         run: |
           sudo apt-get install -y git
           git config --global user.email ${GitHubMail}
           git config --global user.name ${GitHubName}
           git config --global credential.helper store
           echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
           
       - name: Running Ultroid
         timeout-minutes: 350
         continue-on-error: true
         run: |
           git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.CREDS }} ultroid
           cd ultroid
           docker run --privileged --rm -i --env-file .env ubuntu:20.04
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
              cd loop
              echo "1" >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop"
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"${{ secrets.GHUSER }}\r\"
              expect \"Password\"
              send \"${{ secrets.GHPASS }}\r\"
              expect \"main -> main\"
              set timeout -10
              interact"
              
