#Docker Work na BSDK

name: setting up environment

on: [push]
    
env:
  GitHubMail: "error@notavailable.live"
  GitHubName: "ProgrammingError"
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: cloning repo
         continue-on-error: true
         run: |
           sudo apt-get install -y git
           git config --global user.email ${GitHubMail}
           git config --global user.name ${GitHubName}
           git config --global credential.helper store
           echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
           
        
       - name: Misc
         continue-on-error: true
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        
       - name: Running Ultroid
         timeout-minutes: 350
         continue-on-error: true
         run: |
           git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.CREDS }} ultroid
           cd ultroid
           docker build . --file Dockerfile -t ultroid  
           docker run --privileged --rm -i --env-file .env ultroid:latest

       - name: Loop workflow
         continue-on-error: true
         run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
              
